---
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        entry: venv/scripts/ruff.exe
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/jazzband/pip-tools
    rev: 7.3.0
    hooks:
      - id: pip-compile
        name: pip-compile requirements.txt
        entry: venv/scripts/pip-compile.exe
        args: [pyproject.toml]
        files: pyproject.toml
      - id: pip-compile
        name: pip-compile requirements-dev.txt
        entry: venv/scripts/pip-compile.exe
        args: ['--extra', 'ci', '--extra', 'dev', '-o', 'requirements-dev.txt', 'pyproject.toml']
        files: pyproject.toml
      - id: pip-compile
        name: pip-compile requirements-ci.txt
        entry: venv/scripts/pip-compile.exe
        args: ['--extra', 'ci', '-o', 'requirements-ci.txt', 'pyproject.toml']
        files: pyproject.toml
